### ISSUE TITLE
Dependency no longer available?

### ISSUE THREAD

**Issue by bondolo** [infradna/bridge-method-injector#13]
<dependency>
          <groupId>org.jenkins-ci</groupId>
          <artifactId>annotation-indexer</artifactId>
          <version>1.4</version>
    </dependency>

Cannot no longer be found at [https://repo.maven.apache.org/org/jenkins-ci](https://repo.maven.apache.org/org/jenkins-ci)

**Comment by irobertson** [comment]
Odd - https://repo.maven.apache.org/maven2/org/jenkins-ci/ gives a 404, but https://repo.maven.apache.org/maven2/org/jenkins-ci/annotation-indexer/ returns a directory listing showing 1.4, and https://repo.maven.apache.org/maven2/org/jenkins-ci/annotation-indexer/1.4 shows what one would expect.

This seems to be a bug with the maven repo; I'm not sure off hand what their bug reporting system is.

**Comment by irobertson** [comment]
This appears to be fixed. I browsed to https://repo1.maven.org/maven2/org/jenkins-ci/ (note the host), and saw the correct directory listing; after that, browsing to https://repo.maven.apache.org/maven2/org/jenkins-ci/ also works. Apparently browsing to the old repo1.maven.org somehow triggers the (up? down?)-stream repo.maven.apache.org server to get its ducks(*) in a row.

(*) not that Maven uses duck typing...

**Comment by bondolo** [comment]
It does seem to have reappeared.
