### ISSUE TITLE
Version of annotation-indexer is really old

### ISSUE THREAD

**Issue by bondolo** [infradna/bridge-method-injector#18]
Current version is 1.12 vs 1.4 currently used. Main apparent advantage in upgrading is elimination of the javac compiler annotation processor warning:

`[WARNING] warning: Supported source version 'RELEASE_6' from annotation processor 'org.jvnet.hudson.annotation_indexer.AnnotationProcessorImpl' less than -source '1.8'`

**Comment by bondolo** [comment]
ping

**Comment by bondolo** [comment]
ping. This is needed for Java 11 compatibility.

**Comment by davido** [comment]
I add missing repository section in `pom.xml` in #24 .

Wit the PR: #24 i can build `github-api` project with Java 11,
after upgrading bridge-method-injector release there to 1.19.

**Comment by bondolo** [comment]
Now depends on `annotation-indexer` 1.14 https://github.com/infradna/bridge-method-injector/blob/762976d9cc1f3fd63a77e4702e85b9690c4ec4a8/annotation/pom.xml#L16
